using System.Linq;
using System.Text.RegularExpressions;
using Content.Shared.Utopia.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Utopia.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class SalaryConsoleWindow : DefaultWindow
{
    public Action<SalaryPaymentMessage>? OnPaymentRequested;

    private static readonly Regex OnlyNumbersAndMinus = new Regex("[^0-9-]");
    private readonly Dictionary<int, EmployeeEntry> _employeeEntries = new();

    public SalaryConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(BoundUserInterfaceState state)
    {
        if (state is not SalaryConsoleBuiState consoleState)
            return;

        Title = Loc.GetString("salary-console-window-title");

        if (!consoleState.HasCard)
        {
            ShowCardMissingScreen(consoleState.InfoMessage);
            return;
        }

        ShowCardInsertedScreen(consoleState);
    }

    private void ShowCardMissingScreen(string statusMessage)
    {
        StatusLabel.Text = statusMessage;

        BalanceLabel.Visible = false;
        Divider.Visible = false;
        StatusLabel.Visible = true;
        EmployeesScrollContainer.Visible = false;
        NoEmployeesLabel.Visible = false;
    }

    private void ShowCardInsertedScreen(SalaryConsoleBuiState consoleState)
    {
        StatusLabel.Text = consoleState.InfoMessage;

        BalanceLabel.Text = Loc.GetString("salary-console-balance", ("balance", consoleState.AccountBalance));

        BalanceLabel.Visible = true;
        Divider.Visible = true;
        StatusLabel.Visible = true;

        if (consoleState.Employees.Count == 0)
        {
            ShowNoEmployeesMessage();
            return;
        }

        ShowEmployeesList(consoleState.Employees);
    }

    private void ShowNoEmployeesMessage()
    {
        EmployeesScrollContainer.Visible = false;
        NoEmployeesLabel.Text = Loc.GetString("salary-console-no-employees");
        NoEmployeesLabel.Visible = true;
    }

    private void ShowEmployeesList(List<EmployeeData> employees)
    {
        EmployeesScrollContainer.Visible = true;
        NoEmployeesLabel.Visible = false;

        var currentAccountIds = employees.Select(employee => employee.AccountId).ToHashSet();
        var oldAccounts = _employeeEntries.Keys
            .Where(accountId => !currentAccountIds.Contains(accountId))
            .ToList();

        foreach (var oldAccountId in oldAccounts)
        {
            if (_employeeEntries.Remove(oldAccountId, out var entry))
            {
                entry.Container.Orphan();
            }
        }

        foreach (var employee in employees)
        {
            if (!_employeeEntries.TryGetValue(employee.AccountId, out var entry))
            {
                entry = CreateEmployeePanel(employee);
                _employeeEntries[employee.AccountId] = entry;
                EmployeesContainer.AddChild(entry.Container);
            }
            else
            {
                UpdateEmployeePanel(entry, employee);
            }
        }
    }

    private EmployeeEntry CreateEmployeePanel(EmployeeData employee)
    {
        var mainPanel = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(0, 4, 0, 4),
            SeparationOverride = 2
        };

        var infoRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 2)
        };

        var employeeName = new Label
        {
            Text = employee.Name,
            HorizontalExpand = true,
            ClipText = true
        };

        var jobTitle = new Label
        {
            Text = employee.JobTitle,
            HorizontalAlignment = HAlignment.Right,
            Align = Label.AlignMode.Right,
            ClipText = true
        };

        infoRow.AddChild(employeeName);
        infoRow.AddChild(jobTitle);
        mainPanel.AddChild(infoRow);

        var paymentRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 8
        };

        var amountInput = new LineEdit
        {
            PlaceHolder = Loc.GetString("salary-console-amount-placeholder"),
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Left
        };

        var payButton = new Button
        {
            Text = Loc.GetString("salary-console-pay-button"),
            HorizontalAlignment = HAlignment.Right,
            Disabled = true
        };

        amountInput.OnTextChanged += _ =>
        {
            CleanAmountInput(amountInput);
            UpdatePayButton(amountInput, payButton);
        };

        payButton.OnPressed += _ =>
        {
            if (int.TryParse(amountInput.Text, out var amount) && amount != 0)
            {
                OnPaymentRequested?.Invoke(new SalaryPaymentMessage(employee.AccountId, amount));
                amountInput.Text = string.Empty;
                payButton.Disabled = true;
            }
        };

        paymentRow.AddChild(amountInput);
        paymentRow.AddChild(payButton);
        mainPanel.AddChild(paymentRow);

        return new EmployeeEntry
        {
            Container = mainPanel,
            NameLabel = employeeName,
            JobLabel = jobTitle,
            AmountInput = amountInput,
            PayButton = payButton,
            AccountId = employee.AccountId
        };
    }

    private static void UpdateEmployeePanel(EmployeeEntry entry, EmployeeData employee)
    {
        entry.NameLabel.Text = employee.Name;
        entry.JobLabel.Text = employee.JobTitle;
    }

    private static void CleanAmountInput(LineEdit inputField)
    {
        var originalText = inputField.Text;
        var cursorPosition = inputField.CursorPosition;

        var cleanedText = OnlyNumbersAndMinus.Replace(originalText, string.Empty);

        if (cleanedText.StartsWith("-"))
        {
            var numbersAfterMinus = cleanedText[1..];
            cleanedText = "-" + OnlyNumbersAndMinus.Replace(numbersAfterMinus, string.Empty);
        }

        if (cleanedText != originalText)
        {
            inputField.Text = cleanedText;

            var newCursorPosition = Math.Max(0, Math.Min(cursorPosition - (originalText.Length - cleanedText.Length), cleanedText.Length));
            inputField.CursorPosition = newCursorPosition;
        }
    }

    private static void UpdatePayButton(LineEdit amountInput, Button payButton)
    {
        if (string.IsNullOrWhiteSpace(amountInput.Text) || amountInput.Text == "-")
        {
            payButton.Disabled = true;
            return;
        }

        if (int.TryParse(amountInput.Text, out var amount) && amount != 0)
        {
            payButton.Disabled = false;

            if (amount > 0)
            {
                payButton.Text = Loc.GetString("salary-console-pay-button");
            }
            else
            {
                payButton.Text = Loc.GetString("salary-console-deduct-button");
            }
        }
        else
        {
            payButton.Disabled = true;
        }
    }

    private sealed class EmployeeEntry
    {
        public BoxContainer Container = default!;
        public Label NameLabel = default!;
        public Label JobLabel = default!;
        public LineEdit AmountInput = default!;
        public Button PayButton = default!;
        public int AccountId;
    }
}
