using System.Linq;
using System.Text.RegularExpressions;
using Content.Shared.Utopia.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Utopia.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class SalaryConsoleWindow : DefaultWindow
{
    public Action<SalaryPaymentMessage>? OnPaymentRequested;

    private static readonly Regex AmountPattern = new Regex("[^0-9-]");
    private readonly Dictionary<int, EmployeeEntry> _employeeEntries = new();

    public SalaryConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(BoundUserInterfaceState state)
    {
        if (state is not SalaryConsoleBuiState cast)
            return;

        if (!cast.HasCard)
        {
            StatusLabel.Text = cast.InfoMessage;
            BalanceLabel.Visible = false;
            Divider.Visible = false;
            StatusLabel.Visible = true;
            EmployeesScrollContainer.Visible = false;
            NoEmployeesLabel.Visible = false;
            return;
        }

        StatusLabel.Text = cast.InfoMessage;
        BalanceLabel.Text = Loc.GetString("salary-console-balance", ("balance", cast.AccountBalance));
        BalanceLabel.Visible = true;
        Divider.Visible = true;
        StatusLabel.Visible = true;

        if (cast.Employees.Count == 0)
        {
            EmployeesScrollContainer.Visible = false;
            NoEmployeesLabel.Visible = true;
            return;
        }

        EmployeesScrollContainer.Visible = true;
        NoEmployeesLabel.Visible = false;

        var currentAccountIds = cast.Employees.Select(e => e.AccountId).ToHashSet();
        var toRemove = _employeeEntries.Keys.Where(id => !currentAccountIds.Contains(id)).ToList();
        foreach (var accountId in toRemove)
        {
            if (_employeeEntries.TryGetValue(accountId, out var entry))
            {
                entry.Container.Orphan();
                _employeeEntries.Remove(accountId);
            }
        }

        foreach (var employee in cast.Employees)
        {
            if (!_employeeEntries.TryGetValue(employee.AccountId, out var entry))
            {
                entry = CreateEmployeeEntry(employee);
                _employeeEntries[employee.AccountId] = entry;
                EmployeesContainer.AddChild(entry.Container);
            }
            else
            {
                UpdateEmployeeEntry(entry, employee);
            }
        }
    }

    private EmployeeEntry CreateEmployeeEntry(EmployeeData employee)
    {
        var container = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2, 0, 2)
        };

        var infoContainer = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        var nameLabel = new Label
        {
            Text = employee.Name,
            HorizontalExpand = true
        };

        var jobLabel = new Label
        {
            Text = employee.JobTitle,
            HorizontalAlignment = HAlignment.Right
        };

        infoContainer.AddChild(nameLabel);
        infoContainer.AddChild(jobLabel);
        container.AddChild(infoContainer);

        var paymentContainer = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(5, 2, 0, 2)
        };

        var amountEdit = new LineEdit
        {
            PlaceHolder = Loc.GetString("salary-console-amount-placeholder"),
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Left
        };

        amountEdit.OnTextChanged += _ =>
        {
            ValidateAmount(amountEdit);
        };

        var payButton = new Button
        {
            Text = Loc.GetString("salary-console-pay-button"),
            HorizontalAlignment = HAlignment.Right
        };

        payButton.OnPressed += _ =>
        {
            if (int.TryParse(amountEdit.Text, out var amount) && amount != 0)
            {
                OnPaymentRequested?.Invoke(new SalaryPaymentMessage(employee.AccountId, amount));
                amountEdit.Text = string.Empty;
            }
        };

        paymentContainer.AddChild(amountEdit);
        paymentContainer.AddChild(payButton);
        container.AddChild(paymentContainer);

        return new EmployeeEntry
        {
            Container = container,
            NameLabel = nameLabel,
            JobLabel = jobLabel,
            AmountEdit = amountEdit,
            PayButton = payButton,
            AccountId = employee.AccountId
        };
    }

    private static void UpdateEmployeeEntry(EmployeeEntry entry, EmployeeData employee)
    {
        entry.NameLabel.Text = employee.Name;
        entry.JobLabel.Text = employee.JobTitle;
    }

    private static void ValidateAmount(LineEdit lineEdit)
    {
        var amountText = AmountPattern.Replace(lineEdit.Text, string.Empty);

        if (amountText.StartsWith("-"))
        {
            var rest = amountText[1..];
            amountText = "-" + AmountPattern.Replace(rest, string.Empty);
        }
        else
        {
            amountText = AmountPattern.Replace(amountText, string.Empty);
        }

        if (amountText != lineEdit.Text)
        {
            lineEdit.Text = amountText;
        }
    }

    private sealed class EmployeeEntry
    {
        public BoxContainer Container = default!;
        public Label NameLabel = default!;
        public Label JobLabel = default!;
        public LineEdit AmountEdit = default!;
        public Button PayButton = default!;
        public int AccountId;
    }
}
